 ##
## OpenAPI
##
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

##
## JWT
##

jwt.private.key=${JWT_PRIVATE_KEY}
jwt.public.key=${JWT_PUBLIC_KEY}



token.timeout=3600
##
## datasource
##

##H2
spring.h2.console.enabled=true



spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.path=/h2
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sqp=true

##PSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/desofs_db
#spring.datasource.username=username
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

## database schema generation
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true


##
## H2 console for development purposes. e.g., http://localhost:8080/h2-console
##
## for security reasons this setting should be false

##
## MULTIPART (MultipartProperties)
##
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

##
## File Storage Properties
##
# All files uploaded through the REST API will be stored in this directory
#file.upload-dir=/Users/ASUS/Documents/PSOFT/dev
file.upload-dir=./uploads
#file.upload-dir=/Users/franciscoreis/Documents/PSOFT/dev

##
## Logging
##
logging.level.com.example.demo=DEBUG
#logging.level.org.springframework=DEBUG
# ...existing code...

# TLS/SSL connection logging
logging.level.javax.net.ssl=DEBUG
logging.level.sun.security.ssl=DEBUG
logging.level.org.apache.tomcat.util.net=DEBUG
logging.level.org.apache.coyote.http11=DEBUG

##
## Profiles
##
spring.profiles.active=bootstrap,local

server.ssl.key-store=${SSL_KEYSTORE}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat
server.ssl.enabled=false
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2
server.port=8443

### Session Timout
server.servlet.session.timeout=15m
security.login.max-attempts=5
security.login.max-attempts-ip=20
security.login.lock-duration-seconds=300
security.login.ip-block-duration-seconds=300
account.creation.max-attempts=50
##account.creation.time-window=3600
# Import the passwords properties file

spring.config.import=optional:classpath:application-passwords.properties




user.testchicouser=chico
user.adminpassword=${ADMIN_PASS}
user.marketingpassword=${MARKETING_PASS}
user.subscribertomas=${SUBSCRIBER_PASS_1}
user.subscriberalex=${SUBSCRIBER_PASS_2}
user.projectmanagerpassword=${PROJECT_MANAGER}
user.financepassword=${FINANCE_PASSWORD}

spring.datasource.url=${DB_URL}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}






