name: DAST OWASP ZAP Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: 'spotify-copy'
      VERSION: 'latest'
      JAVA_VERSION: '17'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Create .env file from secrets
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env

      - name: Start DB service
        run: docker compose -f docker-compose-db.yml --env-file .env up -d

      - name: Wait for DB to be healthy
        run: |
          for i in {1..20}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose -f docker-compose-db.yml ps -q db))
            echo "DB status: $status"
            if [ "$status" = "healthy" ]; then
              echo "DB is healthy!"
              break
            fi
            sleep 5
            if [ "$i" -eq 20 ]; then
              echo "DB did not become healthy in time."
              docker compose -f docker-compose-db.yml logs
              exit 1
            fi
          done
#      - name: Create database
#        run: |
#          DB_CONTAINER=$(docker compose -f docker-compose-db.yml ps -q db)
#          docker exec -i $DB_CONTAINER psql -U ${{ secrets.DB_USERNAME }} -d postgres <<EOF
#          CREATE DATABASE ${{ secrets.DB_NAME }};
#          \l
#          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose --env-file .env build

      - name: Start app service
        run: docker compose --env-file .env up -d

      - name: Run OWASP ZAP scan
        run: |
          mkdir -p zap-output
          docker run --network="host" \
            -v $(pwd):/zap/wrk/:rw \
           ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html

      - name: Upload ZAP Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/zap_report.html

      - name: Tear down app service
        run: docker compose --env-file .env down --volumes

      - name: Tear down DB service
        run: docker compose -f docker-compose-db.yml down --volumes

      - name: Clean up .env
        run: rm -f .env
