name: DAST OWASP ZAP Scan (No Docker)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write  file
        run: |
          echo "${{ secrets.APPLICATION_PASSWORDS }}" > src/main/resources/application-passwords.properties

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests

      - name: Run Spring Boot app in background
        run: |
          nohup java -jar target/demoOrm-0.0.1-SNAPSHOT.jar &
          sleep 30

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: 'http://localhost:8080'
          failOnRisk: 'high'

      - name: Kill Spring Boot app
        run: pkill -f 'java -jar'
