name: Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
   branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  secret-scanning:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all history

      - name: GitLeaks Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        continue-on-error: true

      - name: Upload GitLeaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: |
            gitleaks-report.json
            gitleaks-report.sarif

  dependency-scanning:
    name: Dependency Vulnerability Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.java.outputs.java-home }}" >> $GITHUB_ENV

      - name: Make mvnw executable
        run: chmod +x ./mvnw
                         
      #Works but has token limit
      - name: Snyk Vulnerability Scanning
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium
        continue-on-error: true

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
            JAVA_HOME: /opt/jdk
        with:
            project: 'spotify-copy'
            path: '.'
            format: 'HTML'
            out: 'reports'
            args: >
              --failOnCVSS 7
              --enableRetired

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
                name: dependency-check-report
                path: reports
